#!/bin/sh

# opout: "open output": A general handler for opening a file's intended output,
# usually the pdf of a compiled document.  I find this useful especially
# running from vim.

basename="$(echo "${*}" | sed 's/\.[^\/.]*$//')"

open "$basename".pdf
